### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by Code-Sploit** [Code-Sploit/V-Sharp#1]
- [ ] Make the server-side application able to constantly receive information from the client and parse it
- [ ] Multithreading clients
- [ ] Encryption (SSL/Self-made)
- [ ] Client interface to acctually use the application
- [ ] Database storage system to store emails
- [ ] Data supply functions for client that can be called from the server
